# Generated by Django 4.0.4 on 2022-05-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='rating',
        ),
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default=0),
        ),
    ]
